### ISSUE TITLE
Assignment 3 Group Project!!!

### ISSUE THREAD

**Issue by YaoTong9190** [YaoTong9190/Bicycling#10]
Since it's a cooperative group work, which part of project are you confident of ?  Due is 30 Nov, Need to be discussed quickly!!!

**Comment by nano1026** [comment]
I think we are fine now... BTW should we detail anything that already in our report..

**Comment by YaoTong9190** [comment]
Yes, I am just faking we're discussing the assignment distribution... pretend we've done before and discussed here....

**Comment by nano1026** [comment]
Yap, they will understand our action. Haha, since we all chat through Wechat or Messenger
