### ISSUE TITLE
Design Material 

### ISSUE THREAD

**Issue by nano1026** [YaoTong9190/Bicycling#11]
Should we also upload the sketch photo? But I left that in my studio. :(

**Comment by YaoTong9190** [comment]
That's Ok, May be Uploaded later😂

**Comment by YaoTong9190** [comment]
fortunately, I found the photo copy
![img_9095](https://user-images.githubusercontent.com/33317738/33569682-5a266544-d922-11e7-9304-537f98efead9.JPG)

**Comment by YaoTong9190** [comment]
Another DISCUSSION DRAFT ! May be helpful
![img_9102 2](https://user-images.githubusercontent.com/33317738/33569752-99e2c7f4-d922-11e7-806f-6e23a5b38116.JPG)

**Comment by sallybai** [comment]
I am in T room, where is your studio? I can help fetch it for you if it is in evolution house

**Comment by nano1026** [comment]
Oh It's okay now, there are two photos here. Thank you
